### ISSUE TITLE
cookie code

### ISSUE THREAD

**Issue by Nienne** [Hex1629/SOCKETEXPLODEv2_DOSTOOL#8]
cookie dont work (data.py error)

**Comment by Hex1629** [comment]
what error

**Comment by Nienne** [comment]
> what error

Generate_url_path () got an unexpected keyword argument "string"

**Comment by Hex1629** [comment]
ok i will fix
what site you want to attack? ( i mean test )

**Comment by Hex1629** [comment]
telegram then https://t.me/IDKOTHERHEX1629
